version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t goapp:latest .
      - docker tag goapp:latest 554248189203.dkr.ecr.us-east-1.amazonaws.com/goapp:new  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 554248189203.dkr.ecr.us-east-1.amazonaws.com/goapp:new

